backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/media/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/static/media" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "Nyheter" # Used in routes, e.g., /admin/collections/blog
    label: "nyhet" # Used in the UI
    folder: "src/routes/app/nyheter" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "nyheter",
        }
      - { label: "title", name: "titel", widget: "string" }
      - { label: "created", name: "skapat av", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
